### ISSUE TITLE
attachement not included

### ISSUE THREAD

**Issue by tatoosh** [manolitto/joplin-mail-gateway#7]
Sending simple Screenshot gets OCR but the attachment is broken/lost. Is that working for you?  The joplin link is not working, maybe the Ressource get delete to fast in tmp?

**Comment by manolitto** [comment]
hmm, yes works for me - but perhaps actually a timing issue and my server is slow enough?  ;-)
have you tried to disable the following line in _joplin-functions.sh ?
rm -r ${TEMP_DIR}

**Comment by tatoosh** [comment]
no thats the wrong part, the ressource exists but the link is wrong:

from your function:

[image.png](resources/0e7e664a08174636913ff3ad1192496e.png)

from gui or `joplin attach <id>  mypic.png`
![e40ce3e5e22199660141c538e750c76b.png](:/07945b9b27784111ac82f2016e9c3691)

Any idea?

**Comment by tatoosh** [comment]
i tried to debug, the problem resovles by this function `addLastImageAsLink`

**Comment by sulazix** [comment]
Hello, 

I have the same issue the link is written 

[1S4 MA 24.03.docx](**resources/**f702ab4bf7834642869aaab9300fbe1c**.docx**)
instead of :
[1S4 MA 24.03.docx](:/f702ab4bf7834642869aaab9300fbe1c)

Any idea how to fix it ?

**Comment by sulazix** [comment]
Ok my Bad, I just start working with Joplin on linux (instead of windows) and it seems that the :/ is the normal way to link resources for Joplin's linux client, and windows client use resources/... 
It's more an issue for Joplin so no need to consider my previous comment.

Thanks a lot again for this script ! Nice job ;-)
